spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none
      show_sql: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/MailOtomation}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
version: 1

management:
  health:
    mail:
      enabled: false

jwt:
  secret: ${JWT_SECRET:CW14ueQBqU0Flp50ImANkSps0Z3Qr6df7p8F40sqDQI=}
