spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/MailOtomation}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
  mail:
        host: smtp.gmail.com
        port: 465
        properties:
          mail.smtp.auth: true
          mail.smtp.ssl.enable: true
          mail.smtp.starttls.enable: false
          mail.smtp.connectiontimeout: 5000
          mail.smtp.timeout: 5000
          mail.smtp.writetimeout: 5000


management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
          exposure:
            include: health,info
  endpoint:
    health:
          show-details: never
security:
  jwt:
    secret: "a-string-secret-at-least-256-bits-long"
    expiration: 3600000
    issuer: "ChartFlowApp"
    cookie-name: "AUTH"
    cookie-secure: "true"
auth:
  default-role: USER

server:
  forward-headers-strategy: native
  servlet:
    session:
      cookie:
        secure: true
        same-site: none


