spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/MailOtomation}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}


management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
          exposure:
            include: health,info
  endpoint:
    health:
          show-details: never
security:
  jwt:
    secret: "a-string-secret-at-least-256-bits-long"
    expiration: 3600000
    issuer: "ChartFlowApp"
    cookie-name: "AUTH"
    cookie-secure: "false"
auth:
  default-role: USER


app:
  cors:
    allowed-origins:
      - http://localhost:5173
      - http://localhost:8080
      - http://127.0.0.1:5173
